
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0

  goos:
  - windows
  - linux
  - darwin

  goarch:
    - amd64
    - arm
    - arm64

  goarm:
    - 6
    - 7

  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: arm
    goarm: 7

archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux

    format_overrides:
      - goos: windows
        format: zip

    files:
      - config_example.json
      - error.mp4
      - templates/*
      - LICENSE
      - README.MD

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'