# .goreleaser.yml
# GoReleaser configuration for torrBotGo
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: torrbot
    main: .
    binary: torrbot
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildDate={{.Date}}
    tags:
      - netgo
      - osusergo

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.MD
      - LICENSE
      - config/config.yaml.example

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: 0x0BSoD
    name: torrBotGo
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    Download the appropriate binary for your system from the assets above.

    ### Linux/macOS
    ```bash
    tar -xzf torrbot_*.tar.gz
    chmod +x torrbot
    ./torrbot --help
    ```

    ### Windows
    Extract the zip file and run `torrbot.exe` from command prompt.

    ## Configuration

    Copy `config/config.yaml.example` to `config/config.yaml` and edit it with your settings.
